Add wandb
jndean/LossRider pull request #1
Opened 2024-08-20 13:57 UTC by scottire

Enables:
```python
linerider_from_wandb(project='pytorch-sweeps-demo', entity='_scott', filters={"display_name": {"$in": ["ethereal-sweep-5"]}})
```

2024-08-20 14:27 UTC, jndean requested changes
Excellent value add 🙏 Minor changes requested

2024-08-20 14:27 UTC, jndean commented on src/lossrider/lossridersrc.py
> +    api = wandb.Api()
```suggestion
    import wandb
    api = wandb.Api()
```

2024-08-20 14:27 UTC, jndean commented on src/lossrider/lossridersrc.py
> +from typing import List, Optional, Dict, Any
Pls move these to the top of the file and omit wandb, I'd prefer not to add that as a dependency for all "users".
If we're being honest pandas should already have been a dependency so I'll accept that addition.

2024-08-21 09:27 UTC, scottire commented
I've added those changes. 🛷

2024-08-21 10:45 UTC, jndean approved these changes
🎿

2024-08-21 10:46 UTC, merged